float64 x       # e.g. Cartesian x coordinate
float64 y       # e.g. Cartesian y coordinate
float64 z       # e.g. Cartesian z coordinate
float64 a       # e.g. Cartesian orientation alpha angle
float64 b       # e.g. Cartesian orientation beta angle
float64 c       # e.g. Cartesian orientation gamma angle
bool boolean_param      # boolean parameter
float64 float_param     # float parameter. E.g. null_space value
---
bool success    # indicate successful run of triggered service
string message  # informational, e.g. for error messages
